### ISSUE TITLE
Taiwan Province is Chinese territory.

### ISSUE THREAD

**Issue by zhoukekestar** [caspg/datamaps.co#1]
Taiwan Province is Chinese territory. But i can't see it on my map.

**Comment by TomHuangCN** [comment]
＋1

**Comment by caspg** [comment]
China map in this project is based on http://www.gadm.org/country shapefile. And there is no Taiwan province.

**Comment by zhoukekestar** [comment]
It's a pity to hear that. But we will see Chinese Developers won't use it until you fixed it. Maybe, I should give you more evidence to support my opinion. Now, there is one reason that Chinese Developers
is not a small part of Github which means you will lose your contributors in China. Ummm... I have to say... it's a hard thing...(⊙﹏⊙)

**Comment by zhoukekestar** [comment]
Yes, we can learn something from Google Maps. There are two domains:
- https://www.google.com/maps
- https://www.google.cn/maps

yeah!

**Comment by motleydev** [comment]
@zhoukekestar I would propose a better solution is to fork the project, and build in a feature to choose a custom shapefile. Asking all people to inherit a data set based on politics is anti-opensource.

This provides added utility and is apolitical.

**Comment by zhoukekestar** [comment]
Sounds great!

**Comment by caspg** [comment]
@motleydev I agree with you and like your idea about custom shapefiles. But this is quite a big feature and :( unfortunately lately, I don't have much time. For now, I simplified process of adding new maps, I'll add step-by-step instructions about adding new maps to README, and would happily accept PRs with new maps 😃

**Comment by stegben** [comment]
We can have debates on whether Taiwan is part of China or not (absolutely not) for years. But it's really funny seeing someone threatening others such way. Especially somebody from a country that [tries to DDoS github](http://arstechnica.com/security/2015/03/github-battles-largest-ddos-in-sites-history-targeted-at-anti-censorship-tools/)

**Comment by zhoukekestar** [comment]
I agree with @motleydev . And that's the solution about this issue.  I'm sorry to intrude on you @caspg.  Yep, your project is awesome. Thanks anyway. For you, Mr. @stegben , I'd like to talk with you in chinese .

> 君子务本，本立而道生
> by Confucius.

**Comment by stegben** [comment]
Thanks for your invitation, but no. As I mentioned, the talk might last for years. Nobody have time for that. 

By the way, citing a rather irrelevant ancient quote does not make your words more persuasive.

p.s. @caspg thanks for such a great project. I apologize if this discussion bothers you.
