### ISSUE TITLE
Cannot Upload a CSV File

### ISSUE THREAD

**Issue by cart587** [caspg/datamaps.co#2]
Hello,

I am trying to use your sample project. After running the npm install and start commands I load localhost:3030. When I go to the editor page and click a map, nothing happens. Only two buttons show up: "Save SVG" and "Save PNG," but I don't see anything about uploading data.

<img width="959" alt="datamaps screenshot" src="https://cloud.githubusercontent.com/assets/6404276/16014436/f230b848-3145-11e6-92a9-98036c2f7cae.PNG">

**Comment by caspg** [comment]
You will see "upload csv" button when you select map.
