### ISSUE TITLE
Add documentation about how to add maps

### ISSUE THREAD

**Issue by jpgreth** [caspg/datamaps.co#5]
It would be great to have an "how to" showing the steps what to do to add other maps.

Having this would make it much easier to contribute more maps or even more detailed maps (e.g. counties of a [federal] state - in OSM it would be admin_level=6)

**Comment by caspg** [comment]
Hey. Documentation is updated, unfortunately it is not the best one.  Right now I don't have time to work on this project, but I'll resume my work in mid September.
