### ISSUE TITLE
How can i install Devtools

### ISSUE THREAD

**Issue by AndyLicht** [caspg/datamaps.co#6]
I get an empty site of your map-project, in my browser console i get the following error:

Download the React DevTools for a better development experience: https://fb.me/react-devtools
app.bundle.js:103668 Uncaught Error: Cannot find module "../Devtools"webpackMissingModule @ app.bundle.js:103668(anonymous function) @ app.bundle.js:103668__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:46917(anonymous function) @ app.bundle.js:46919__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:74(anonymous function) @ app.bundle.js:90__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:47__webpack_require__ @ app.bundle.js:20(anonymous function) @ app.bundle.js:40(anonymous function) @ app.bundle.js:43

In which directory i have to copy the devtools (https://facebook.github.io/react/downloads.html) an which version i have to use?

Thanks for this great project!!!!

**Comment by caspg** [comment]
You should follow https://github.com/caspg/datamaps.co#development.
