### ISSUE TITLE
Maps aren't showing up for local instance

### ISSUE THREAD

**Issue by DavidLemayian** [caspg/datamaps.co#8]
Hi. Great project. Was working on adding a map and received the following error in browser console locally:

```
app.bundle.js:61248 Uncaught (in promise) TypeError: Cannot read property 'feature' of undefined(…)
(anonymous function) @ app.bundle.js:61248
```

Which points to this:

``` js
var topoJSONFeatures = _topojson2.default.feature(topoJSONData, topoJSONData.objects[mapType]).features;
```

Any idea what could be causing this?

**Comment by caspg** [comment]
There is some issue with importing `topojson` [here](https://github.com/caspg/datamaps.co/blob/591afa9a3187dca792f663a6e76449e47cf98b54/src/redux/actions/topoData.js#L2). 

To fix this you can change 
`import topojson from 'topojson'` to `const topojson = require('topojson')`

**Comment by caspg** [comment]
Fixed https://github.com/caspg/datamaps.co/commit/18d506aeb4e796301489e36b2ebeec2c6890c8a7
